#!/bin/bash
#   Request 1 processors on 1 node
#  
#PBS -l nodes=1:ppn=1
#
#   Request 8 hours of walltime
#
#PBS -l walltime=6:00:00
#
#   Request 8 gigabyte of memory per process
#
#PBS -l pmem=4gb
#
#   Request that regular output and terminal output go to the same file
#
#PBS -j oe
#
#   Loop 17 times
#
#PBS -t 361-432

module load matlab
cd /gpfs/group/nad12/default/nad12/FAME8/RSA/scripts
matlab-bin -nodisplay -nosplash -r "run_rsa(${PBS_ARRAYID});"

