#!/bin/bash
#   Request 1 processors on 1 node
#  
#PBS -l nodes=1:ppn=1
#
#   Request 12 hours of walltime
#
#PBS -l walltime=12:00:00
#
#   Request 4 gigabyte of memory per process
#
#PBS -l pmem=4gb
#
#   Request that regular output and terminal output go to the same file
#
#PBS -j oe
#
#   Loop 40 times
#
#PBS -t 1-40

module load matlab
cd /gpfs/group/nad12/default/nad12/FAME8/RSA/updated-scripts
matlab -nodisplay -nosplash -r "run_ers_searchlight(${PBS_ARRAYID});"
